package com.oneapp.incture.pmc.poadapter.services;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "PMCProcessManagementFacade", targetNamespace = "http://oneapp.com/incture/pmc/poadapter/services/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface PMCProcessManagementFacade {

  /**
   * Java representation of web method [getProcessDetails].
   */
  @javax.jws.WebMethod(operationName = "getProcessDetails")
  @javax.xml.ws.RequestWrapper(localName = "getProcessDetails", targetNamespace = "http://oneapp.com/incture/pmc/poadapter/services/", className = "com.oneapp.incture.pmc.poadapter.services.GetProcessDetails")
  @javax.xml.ws.ResponseWrapper(localName = "getProcessDetailsResponse", targetNamespace = "http://oneapp.com/incture/pmc/poadapter/services/", className = "com.oneapp.incture.pmc.poadapter.services.GetProcessDetailsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.oneapp.incture.pmc.poadapter.services.ProcessEventsDto getProcessDetails(@javax.jws.WebParam(name = "processInstanceId", targetNamespace = "") java.lang.String processInstanceId);

  /**
   * Java representation of web method [getTaskDetails].
   */
  @javax.jws.WebMethod(operationName = "getTaskDetails")
  @javax.xml.ws.RequestWrapper(localName = "getTaskDetails", targetNamespace = "http://oneapp.com/incture/pmc/poadapter/services/", className = "com.oneapp.incture.pmc.poadapter.services.GetTaskDetails")
  @javax.xml.ws.ResponseWrapper(localName = "getTaskDetailsResponse", targetNamespace = "http://oneapp.com/incture/pmc/poadapter/services/", className = "com.oneapp.incture.pmc.poadapter.services.GetTaskDetailsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.oneapp.incture.pmc.poadapter.services.TaskEventsDto getTaskDetails(@javax.jws.WebParam(name = "taskInstanceId", targetNamespace = "") java.lang.String taskInstanceId);

}
