package com.incture.pmc.poadapter.services;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "CustomAttributesService", targetNamespace = "http://incture.com/pmc/poadapter/services/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface CustomAttributesService {

  /**
   * Java representation of web method [getCustomAttributes].
   */
  @javax.jws.WebMethod(operationName = "getCustomAttributes")
  @javax.xml.ws.RequestWrapper(localName = "getCustomAttributes", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetCustomAttributes")
  @javax.xml.ws.ResponseWrapper(localName = "getCustomAttributesResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetCustomAttributesResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.CustomAttributeDto getCustomAttributes(@javax.jws.WebParam(name = "taskId", targetNamespace = "") java.lang.String taskId);

}
