package com.incture.pmc.poadapter.services;

/**
 * Service implementation of {CustomAttributesServiceService} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "CustomAttributesServiceService", targetNamespace = "http://incture.com/pmc/poadapter/services/", wsdlLocation = "META-INF/wsdl/com/incture/pmc/poadapter/services/rootwsdl_CustomAttributesServiceService/rootwsdl_CustomAttributesServiceService.wsdl")
public class CustomAttributesServiceService extends javax.xml.ws.Service {

  private final static java.net.URL CUSTOMATTRIBUTESSERVICESERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public CustomAttributesServiceService() throws java.net.MalformedURLException {
    super(CUSTOMATTRIBUTESSERVICESERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://incture.com/pmc/poadapter/services/", "CustomAttributesServiceService"));
  }
  public CustomAttributesServiceService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [CustomAttributesServicePort].
   */
  @javax.xml.ws.WebEndpoint(name = "CustomAttributesServicePort")
  public com.incture.pmc.poadapter.services.CustomAttributesService getCustomAttributesServicePort() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://incture.com/pmc/poadapter/services/","CustomAttributesServicePort");
    return (com.incture.pmc.poadapter.services.CustomAttributesService) super.getPort(portName,com.incture.pmc.poadapter.services.CustomAttributesService.class);
  }
}
