package com.incture.pmc.poadapter.services;

/**
 * Service implementation of {processActionFacadeService} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "processActionFacadeService", targetNamespace = "http://incture.com/pmc/poadapter/services/", wsdlLocation = "META-INF/wsdl/com/incture/pmc/poadapter/services/rootwsdl_processActionFacadeService/rootwsdl_processActionFacadeService.wsdl")
public class ProcessActionFacadeService extends javax.xml.ws.Service {

  private final static java.net.URL PROCESSACTIONFACADESERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public ProcessActionFacadeService() throws java.net.MalformedURLException {
    super(PROCESSACTIONFACADESERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://incture.com/pmc/poadapter/services/", "processActionFacadeService"));
  }
  public ProcessActionFacadeService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [processActionFacadePort].
   */
  @javax.xml.ws.WebEndpoint(name = "processActionFacadePort")
  public com.incture.pmc.poadapter.services.ProcessActionFacade getProcessActionFacadePort() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://incture.com/pmc/poadapter/services/","processActionFacadePort");
    return (com.incture.pmc.poadapter.services.ProcessActionFacade) super.getPort(portName,com.incture.pmc.poadapter.services.ProcessActionFacade.class);
  }
}
