package com.incture.pmc.poadapter.services;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "processActionFacade", targetNamespace = "http://incture.com/pmc/poadapter/services/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface ProcessActionFacade {

  /**
   * Java representation of web method [cancelProcess].
   */
  @javax.jws.WebMethod(operationName = "cancelProcess")
  @javax.xml.ws.RequestWrapper(localName = "cancelProcess", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.CancelProcess")
  @javax.xml.ws.ResponseWrapper(localName = "cancelProcessResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.CancelProcessResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.lang.String cancelProcess(@javax.jws.WebParam(name = "processInstanceId", targetNamespace = "") java.lang.String processInstanceId);

}
