package com.incture.pmc.poadapter.services;

/**
 * Service implementation of {SubstitutionProfileManagerFacadeService} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "SubstitutionProfileManagerFacadeService", targetNamespace = "http://incture.com/pmc/poadapter/services/", wsdlLocation = "META-INF/wsdl/com/incture/pmc/poadapter/services/rootwsdl_SubstitutionProfileManagerFacadeService/rootwsdl_SubstitutionProfileManagerFacadeService.wsdl")
public class SubstitutionProfileManagerFacadeService extends javax.xml.ws.Service {

  private final static java.net.URL SUBSTITUTIONPROFILEMANAGERFACADESERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public SubstitutionProfileManagerFacadeService() throws java.net.MalformedURLException {
    super(SUBSTITUTIONPROFILEMANAGERFACADESERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://incture.com/pmc/poadapter/services/", "SubstitutionProfileManagerFacadeService"));
  }
  public SubstitutionProfileManagerFacadeService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [SubstitutionProfileManagerFacadePort].
   */
  @javax.xml.ws.WebEndpoint(name = "SubstitutionProfileManagerFacadePort")
  public com.incture.pmc.poadapter.services.SubstitutionProfileManagerFacade getSubstitutionProfileManagerFacadePort() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://incture.com/pmc/poadapter/services/","SubstitutionProfileManagerFacadePort");
    return (com.incture.pmc.poadapter.services.SubstitutionProfileManagerFacade) super.getPort(portName,com.incture.pmc.poadapter.services.SubstitutionProfileManagerFacade.class);
  }
}
