package com.incture.pmc.poadapter.services;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "SubstitutionManagementFacade", targetNamespace = "http://incture.com/pmc/poadapter/services/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface SubstitutionManagementFacade {

  /**
   * Java representation of web method [createRule].
   */
  @javax.jws.WebMethod(operationName = "createRule")
  @javax.xml.ws.RequestWrapper(localName = "createRule", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.CreateRule")
  @javax.xml.ws.ResponseWrapper(localName = "createRuleResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.CreateRuleResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.ResponseDto createRule(@javax.jws.WebParam(name = "ruleDto", targetNamespace = "") com.incture.pmc.poadapter.services.SubstitutionRuleDto ruleDto);

  /**
   * Java representation of web method [getSubstitutedUsers].
   */
  @javax.jws.WebMethod(operationName = "getSubstitutedUsers")
  @javax.xml.ws.RequestWrapper(localName = "getSubstitutedUsers", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetSubstitutedUsers")
  @javax.xml.ws.ResponseWrapper(localName = "getSubstitutedUsersResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetSubstitutedUsersResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.UserDto> getSubstitutedUsers(@javax.jws.WebParam(name = "substitutingUserString", targetNamespace = "") java.lang.String substitutingUserString);

  /**
   * Java representation of web method [getSubstituteUsers].
   */
  @javax.jws.WebMethod(operationName = "getSubstituteUsers")
  @javax.xml.ws.RequestWrapper(localName = "getSubstituteUsers", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetSubstituteUsers")
  @javax.xml.ws.ResponseWrapper(localName = "getSubstituteUsersResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetSubstituteUsersResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.UserDto> getSubstituteUsers(@javax.jws.WebParam(name = "substituteUserString", targetNamespace = "") java.lang.String substituteUserString);

  /**
   * Java representation of web method [getActiveRulesBySubstitute].
   */
  @javax.jws.WebMethod(operationName = "getActiveRulesBySubstitute")
  @javax.xml.ws.RequestWrapper(localName = "getActiveRulesBySubstitute", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetActiveRulesBySubstitute")
  @javax.xml.ws.ResponseWrapper(localName = "getActiveRulesBySubstituteResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetActiveRulesBySubstituteResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.SubstitutionRuleDto> getActiveRulesBySubstitute(@javax.jws.WebParam(name = "substitutingUser", targetNamespace = "") java.lang.String substitutingUser);

  /**
   * Java representation of web method [getActiveRulesBySubstitutedUser].
   */
  @javax.jws.WebMethod(operationName = "getActiveRulesBySubstitutedUser")
  @javax.xml.ws.RequestWrapper(localName = "getActiveRulesBySubstitutedUser", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetActiveRulesBySubstitutedUser")
  @javax.xml.ws.ResponseWrapper(localName = "getActiveRulesBySubstitutedUserResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetActiveRulesBySubstitutedUserResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.SubstitutionRuleDto> getActiveRulesBySubstitutedUser(@javax.jws.WebParam(name = "substitutedUser", targetNamespace = "") java.lang.String substitutedUser);

  /**
   * Java representation of web method [getInactiveRulesBySubstitute].
   */
  @javax.jws.WebMethod(operationName = "getInactiveRulesBySubstitute")
  @javax.xml.ws.RequestWrapper(localName = "getInactiveRulesBySubstitute", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetInactiveRulesBySubstitute")
  @javax.xml.ws.ResponseWrapper(localName = "getInactiveRulesBySubstituteResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetInactiveRulesBySubstituteResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.SubstitutionRuleDto> getInactiveRulesBySubstitute(@javax.jws.WebParam(name = "substitutingUser", targetNamespace = "") java.lang.String substitutingUser);

  /**
   * Java representation of web method [getInactiveRulesBySubstitutedUser].
   */
  @javax.jws.WebMethod(operationName = "getInactiveRulesBySubstitutedUser")
  @javax.xml.ws.RequestWrapper(localName = "getInactiveRulesBySubstitutedUser", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetInactiveRulesBySubstitutedUser")
  @javax.xml.ws.ResponseWrapper(localName = "getInactiveRulesBySubstitutedUserResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetInactiveRulesBySubstitutedUserResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.SubstitutionRuleDto> getInactiveRulesBySubstitutedUser(@javax.jws.WebParam(name = "substitutedUser", targetNamespace = "") java.lang.String substitutedUser);

  /**
   * Java representation of web method [getRulesBySubstitutedUser].
   */
  @javax.jws.WebMethod(operationName = "getRulesBySubstitutedUser")
  @javax.xml.ws.RequestWrapper(localName = "getRulesBySubstitutedUser", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetRulesBySubstitutedUser")
  @javax.xml.ws.ResponseWrapper(localName = "getRulesBySubstitutedUserResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetRulesBySubstitutedUserResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.SubstitutionRuleDto> getRulesBySubstitutedUser(@javax.jws.WebParam(name = "user", targetNamespace = "") java.lang.String user);

  /**
   * Java representation of web method [getRulesBySubstitute].
   */
  @javax.jws.WebMethod(operationName = "getRulesBySubstitute")
  @javax.xml.ws.RequestWrapper(localName = "getRulesBySubstitute", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetRulesBySubstitute")
  @javax.xml.ws.ResponseWrapper(localName = "getRulesBySubstituteResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetRulesBySubstituteResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.SubstitutionRuleDto> getRulesBySubstitute(@javax.jws.WebParam(name = "user", targetNamespace = "") java.lang.String user);

  /**
   * Java representation of web method [updateRule].
   */
  @javax.jws.WebMethod(operationName = "updateRule")
  @javax.xml.ws.RequestWrapper(localName = "updateRule", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.UpdateRule")
  @javax.xml.ws.ResponseWrapper(localName = "updateRuleResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.UpdateRuleResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.ResponseDto updateRule(@javax.jws.WebParam(name = "ruleDto", targetNamespace = "") com.incture.pmc.poadapter.services.SubstitutionRuleDto ruleDto);

  /**
   * Java representation of web method [deleteRule].
   */
  @javax.jws.WebMethod(operationName = "deleteRule")
  @javax.xml.ws.RequestWrapper(localName = "deleteRule", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.DeleteRule")
  @javax.xml.ws.ResponseWrapper(localName = "deleteRuleResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.DeleteRuleResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.ResponseDto deleteRule(@javax.jws.WebParam(name = "ruleDto", targetNamespace = "") com.incture.pmc.poadapter.services.SubstitutionRuleDto ruleDto);

}
