package com.incture.pmc.poadapter.services;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "SubstitutionProfileManagerFacade", targetNamespace = "http://incture.com/pmc/poadapter/services/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface SubstitutionProfileManagerFacade {

  /**
   * Java representation of web method [createSubstitutionProfile].
   */
  @javax.jws.WebMethod(operationName = "createSubstitutionProfile")
  @javax.xml.ws.RequestWrapper(localName = "createSubstitutionProfile", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.CreateSubstitutionProfile")
  @javax.xml.ws.ResponseWrapper(localName = "createSubstitutionProfileResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.CreateSubstitutionProfileResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.SubstitutionProfileResponse createSubstitutionProfile(@javax.jws.WebParam(name = "profileDto", targetNamespace = "") com.incture.pmc.poadapter.services.SubstitutionProfileDto profileDto);

  /**
   * Java representation of web method [getAllProfiles].
   */
  @javax.jws.WebMethod(operationName = "getAllProfiles")
  @javax.xml.ws.RequestWrapper(localName = "getAllProfiles", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetAllProfiles")
  @javax.xml.ws.ResponseWrapper(localName = "getAllProfilesResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetAllProfilesResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.SubstitutionProfileResponse getAllProfiles();

  /**
   * Java representation of web method [deleteProfile].
   */
  @javax.jws.WebMethod(operationName = "deleteProfile")
  @javax.xml.ws.RequestWrapper(localName = "deleteProfile", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.DeleteProfile")
  @javax.xml.ws.ResponseWrapper(localName = "deleteProfileResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.DeleteProfileResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.ResponseDto deleteProfile(@javax.jws.WebParam(name = "profileId", targetNamespace = "") java.lang.String profileId);

  /**
   * Java representation of web method [getProfileById].
   */
  @javax.jws.WebMethod(operationName = "getProfileById")
  @javax.xml.ws.RequestWrapper(localName = "getProfileById", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetProfileById")
  @javax.xml.ws.ResponseWrapper(localName = "getProfileByIdResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetProfileByIdResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.SubstitutionProfileResponse getProfileById(@javax.jws.WebParam(name = "profileId", targetNamespace = "") java.lang.String profileId);

  /**
   * Java representation of web method [getProfileByKey].
   */
  @javax.jws.WebMethod(operationName = "getProfileByKey")
  @javax.xml.ws.RequestWrapper(localName = "getProfileByKey", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetProfileByKey")
  @javax.xml.ws.ResponseWrapper(localName = "getProfileByKeyResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetProfileByKeyResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.SubstitutionProfileResponse getProfileByKey(@javax.jws.WebParam(name = "profileKey", targetNamespace = "") java.lang.String profileKey);

  /**
   * Java representation of web method [getMyTaskModelIds].
   */
  @javax.jws.WebMethod(operationName = "getMyTaskModelIds")
  @javax.xml.ws.RequestWrapper(localName = "getMyTaskModelIds", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetMyTaskModelIds")
  @javax.xml.ws.ResponseWrapper(localName = "getMyTaskModelIdsResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetMyTaskModelIdsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<com.incture.pmc.poadapter.services.TaskModelDto> getMyTaskModelIds();

  /**
   * Java representation of web method [getTaskModel].
   */
  @javax.jws.WebMethod(operationName = "getTaskModel")
  @javax.xml.ws.RequestWrapper(localName = "getTaskModel", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetTaskModel")
  @javax.xml.ws.ResponseWrapper(localName = "getTaskModelResponse", targetNamespace = "http://incture.com/pmc/poadapter/services/", className = "com.incture.pmc.poadapter.services.GetTaskModelResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public com.incture.pmc.poadapter.services.TaskModelDto getTaskModel(@javax.jws.WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0);

}
