package com.incture.pmc.poadapter.services;

/**
 * Service implementation of {WorkBoxActionFacadeService} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "WorkBoxActionFacadeService", targetNamespace = "http://incture.com/pmc/poadapter/services/", wsdlLocation = "META-INF/wsdl/com/incture/pmc/poadapter/services/rootwsdl_WorkBoxActionFacadeService/rootwsdl_WorkBoxActionFacadeService.wsdl")
public class WorkBoxActionFacadeService extends javax.xml.ws.Service {

  private final static java.net.URL WORKBOXACTIONFACADESERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public WorkBoxActionFacadeService() throws java.net.MalformedURLException {
    super(WORKBOXACTIONFACADESERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://incture.com/pmc/poadapter/services/", "WorkBoxActionFacadeService"));
  }
  public WorkBoxActionFacadeService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [WorkBoxActionFacadePort].
   */
  @javax.xml.ws.WebEndpoint(name = "WorkBoxActionFacadePort")
  public com.incture.pmc.poadapter.services.WorkBoxActionFacade getWorkBoxActionFacadePort() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://incture.com/pmc/poadapter/services/","WorkBoxActionFacadePort");
    return (com.incture.pmc.poadapter.services.WorkBoxActionFacade) super.getPort(portName,com.incture.pmc.poadapter.services.WorkBoxActionFacade.class);
  }
}
